id: twitter-stream-controller
apiVersion: v1beta1
kind: ReplicationController
desiredState:
  replicas: 1
  # replicaSelector identifies the set of Pods that this
  # replicaController is responsible for managing
  replicaSelector:
    name: twitter-stream
  # podTemplate defines the 'cookie cutter' used for creating
  # new pods when necessary
  podTemplate:
    desiredState:
      manifest:
        version: v1beta1
        id: twitter-stream
        containers:
          - name: twitter-to-pubsub
            # Change this to point to your docker image
            image: gcr.io/your-project/your-image-tag
            env:
              - name: PROCESSINGSCRIPT
                value: twitter-to-pubsub
              # Change this to your pubsub topic
              - name: PUBSUB_TOPIC
                value: projects/your-project/topics/your-topic
              # Change the following four settings to your twitter credentials
              # information.
              - name: CONSUMERKEY
                value: xxxx
              - name: CONSUMERSECRET
                value: xxxx
              - name: ACCESSTOKEN
                value: xxxx
              - name: ACCESSTOKENSEC
                value: xxxx
              - name: TWSTREAMMODE
                value: sample
    # Important: these labels need to match the selector above
    # The api server enforces this constraint.
    labels:
      name: twitter-stream
